[package]
name = "web_scraper"
version = "0.1.0"
authors = ["Ciaran Doherty <cad106uk@gmail.com>"]

[lib]
name = "web_scraper"
crate-type = ["dylib"]

[dependencies]
hyper = "0.6"
libc = "0.1"
html5ever = "0.2"
tendril = "0.1"
string_cache = "0.2"
url = "0.5"
